name: Build and Develop

#on:
#  push:
#    branches:
#      - develop/waggle-1.0.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Packages build
        id: build-packages
        run: pnpm run build:packaged

      - name: Run API App build
        run: pnpm run build:api